dist: xenial
language: python
python: 3.7
install:
- pip install -e '.[dev]'
script:
- ./scripts/quality-check.sh 
after_success:
- codecov
notifications:
  slack:
    on_success: always
    on_failure: always
    template:
    - Build (<%{build_url}|#%{build_number}>) *%{result}* on branch `%{branch}` with
      commit (<%{compare_url}|%{commit}>).
    - 'Author: %{author}'
    - 'Execution time: *%{duration}*'
    - 'Message: %{message}'
    rooms:
      secure: oZ711pEg58m/oNNNNMP+CcriQDgFdoMs4pd4KiTK/hzihggsFa2FcjWqlGDUylcUxaPpLjBp1o4qtC3ZlXUBD/dtPhVl+vHWkgxQy4q/4n6n+9+HFwKm3Frq+Qii0DkBfjQoAIAxfufLOCz/V3UFPe67Yh3nd3ptYIJQy38TK3r9OLF8bQcHKl2Eol2SlPQufImucO/qrN7xIMpa6wxjRmC10ek4wUsCwDo6ChefaVPK0lwj1msFdYvspp/PnVbdTmqE2XwLGkSdLYqb+Wk5FhQC9whMgTwhRLRw9yntDegSORIyG2dpvIwhYx8nVymoi24fmOinxGzgo5sZGL7fJC2WEejWLLmJYJOaqdgtjlaTIJrLbIZlmHIM0LO8gpkMTWFCrWSFZXts4cPiZAFZIHSKvUK+dAcq2BzYHwF5WA34kUoi5s8PyQ2fFTEmZ2/DqC+UIqZq5SOt3n5kIt32ZE5ke1DmvvBci5WgRi3KWlJBavQho7B3HdRm9bAuLiNSxlT3UUg10IlHGfiMoNoqvpNF+6Tn6j6PDlCIH3kGVt1bMPDaFYtNUYAD221gLbiykT5Ve/q3LQmckVLItji5azsN5QXorxy+gsFdVgKJc55FiIhtGAa2dKYlsdx4IdmJ6/7ep/QY723dAoi4eM/DlChqxUvrr0u/WaXlwO6Rgss=
