dist: xenial
language: python
python: 3.7
install:
- pip install -r requirements.txt
script:
- flake8 kdlc/ tests/ setup.py
- black --check kdlc tests setup.py
- pytest --cov=./
after_success:
- codecov
notifications:
  slack:
    secure: IFXZEg5T4+kA8dIfuA8BDzGLGf199Evy/U6Ro0pj5V50oSXhN3WDqg/vTuoagrxwseNSq3LMRYy80dU4VxUvQBw5aoaIcRYvkWfLro1s3Hlb9v7Jup0PHy8SAT4ZC0z6NTedInf9wJBpaoTFcck0dpXAXT4oy0ExSgyIlz9KFJYhSEWkilA3niiJEzfgabXfXGIYajqY6uwPz3hEXhhY+E0eMHhn2EsCP+9yKbp6DEUYYVun6rsnOhzs0MUyqfQLOwbE0DgkKoXG5fHnsmwb4gu4bNmBlsFDoaTMSgyLRn4T2ASR+5iVbbqPW9YMFw5H2wNgnQfvjA2/vNcVvBqRkQxxk/CvcsoD0dMhD0HZPwSh4ABA9fkATEENz6sri9IbTWWwbyw9YN5hWp6nA0jTGiyyTXLmVG7Wcq63arxG5jqheM9vO1VRUkF5TvGQaVSmWHtyoRZxLqkWf0t4ocXvx7ZkxVXovSIKxyT5/NBpqXyq3GvZCOv6cLT2BWAPx6RW9r0A1fH8TcT66bj8ayNZYDYr7YW2lbIuT2r4HnnOeHmyjujl65CnEnngGC38jRKZguXvmMpaL5+syidINBcy4xUUC3isEHbYnJg4Cr7e7JxWD/ZKbp7rZnq2r6xUmdM7wHF9OF/1sCBWDIhUga4DrmnhqmwZNxj4cARXmnj79/o=
    on_success: always
    on_failure: always
    template:
      - "Build (<%{build_url}|#%{build_number}>) *%{result}* on branch `%{branch}` with commit (<%{compare_url}|%{commit}>)."
      - "Author: %{author}"
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
