dist: xenial
language: python
python: 3.7
install:
- pip install -r requirements.txt
script:
- flake8 kdlc/ tests/ setup.py
- black --check kdlc tests setup.py
- pytest --cov=./
after_success:
- codecov
notifications:
  slack:
    secure: 7YYqWG+wyJBgfopxBuwLFpWp4+cv7/Gun8iLFGTYZUB/wt0YHmQej8L1JHyGyeU45F7O8DIvmfITcwAZq95u4+jvCDyTbBgRn49pJ6XrM8WQ+K6GxInkf4XzTUAL690SBGsdRBPox141USlAwBggkl9Fw9glrByQNJv7E8jl/Ci7FiVqMhXolEMXTjz0xRz4qT0yyHFfMW7XDOZw5pE7ZN5mRESLu/zSR5sVX0/M6Cy7DXZjvuS15Yc8MABNldxq1K9LljaN7k/VJ5eHw+u/j9CEmA92HqoNkz4mHXi21OZiheRb3QF5hTmCd26a9h5pFelEicQzE1MYVCixpVJMsG6SCtEh5o0RfjpRHe5caU6jww0E1ctDMhMWIoikkdFElhA+yK5j7+nyGUuXM6Q4NddBe/vH8qGxQS6pmU3Q0dXICU6orha0439lW5UCjdgW9IWXvUrx1NkRH3PhfGKxlX1qv2YqI0UgYlXH2fIcCp1FJcI7p6yVXNRfX22x7XSqex0Q9zQyD3fT+QI2AWGsCb2K2KbZqbCXZfhxZFtQlA+t+vV5dw1ufwHXN/+74gr85ItdSJdVgmczDyQiCyYH7Qw+AK21mc/LfLN0A4D5JXveCQMxptN7VALqEMUoi1vxkjewFrth4ghVH+BeFcno1SmZQUYsvo/xrJ72wp4wL7k=
