dist: xenial
language: python
python: 3.7
install:
- pip install -r requirements.txt
script:
- flake8 kdlc/ tests/ setup.py
- black --check kdlc tests setup.py
- pytest --cov=./
after_success:
- codecov
notifications:
  slack:
    secure: I7Dovcg2xZjyAxQ3SPRO/ZympcjUvVvX9YBTk/B3v6XuR2nAXaccYGqoxQ0pvmXciA6Wj5TTNqaJm1XTsG6UqGts8MRRApTr+3jJAnxzCsra1c9DDEX7bmTwGl1JD4Lo02udlMTSGHfoO7l7FfLdAZEJ4Hic3h8urJF70zRmW6ohrCteBG4xYUZvuZO/DTGTGbaTD894+Rn1FTXzRKHLbWw+kU0HuHLY++MJLVYH29DUgWiJ55OBkEb9U2xwxNw6lSveyyIrMEE9KQtuTo3MvyUDOktg8PYUBkrwvyb+UsgIpHm8lqTrduv9EUvF9/TYTMrHuz5bdjjdnUFhgEVSMLeTIjedEgRDaoKcAFi2yeSPjWxBIm+Xth1ndjMvrvrhC3c6LcbIjEhz3fkw9gppDIX5qf/ZF3I8avrBTpq1TuZ66W3VLlmlARuUTWHFBCln3XlcyfsrbFqO6Wwc5Ej3sMgTws43H0CWSP+O/yO4ckBz5iMKuQw54Xx43BtDHS3+gAjgERirOW7SSK5Az3CaI2GL4/tkKdnFD65P4eGiOrVSg28RZxssjkTHtObZJ2mHwKIAI7KyBgSmJ1Md7VMOf+ah/hLDAOl1B2Wz9aH0NH1Hs84cD0EIL7wmpHV2/jI/gBDvQ9dRlXS1sua4nV4DN761fAecVaiBrcjd/9m5hyY=
    rooms:
      secure: 4xLdX19fBjSvK5CsIIswWlyPVi8J5W2W/q5kfBqoG10BGmVSNvgP+DH5FKCVRzTG6Lr4YIUg7HyIorZLGSmKE9tka6v4Adm3ZrLwYLBZ1Weo6csRiJGh2Rdw4WCkrhDgxxcvXnXzV/n+sGgAaU3/aTTrOHQRHOU0WpQctf8mpdDoX7/LJqXdrnSqu+wEA9ApGIJcBBAxF6jzIc5oIf7jooeBPnbjUOEcHvHc4bgfDBiHiTrV6lXHkMFkV7AM1rcYpNfY88MgOwVfmSd3yMYvi4h5Rihe00py9PK0Ee8E3ce+aPe8usDMVbft3shwHfwmWdOOKajvIHRsPCCGxhVDgdkR1irGZ4IyLaI4la3yZDisu7ld9fYfOar4GqWVF/h51bPeHbeGVlyMipIIY3d7LLRngAiJQo+5HJVHYarnplDC+3Gb6g1SUDdH/ZV+WZtHPPEHfHvNNEym0UoXMuAozGFWqDBKU1cUKC2OnM4165RcuOrpluDSAQakzM4OuvE7tmygDMG+QtlRZVH9+oTi4HFRGc1lL73UW3ABgOFQdo2iHzd59FInyOMDullzJ3lvyfQhploxXzrU5suEzV0IyrP22C4s9rZA/CRtgGYjZ1ULcTbRJY6KFGY+4li3oKwlt7/eNtysarcCHiwpr22OgGT5YP88wdSsxKFB9RpfHtM=
