dist: xenial
language: python
python: 3.7
install:
- pip install -r requirements.txt
script:
- flake8 kdlc/ tests/ setup.py
- black --check kdlc tests setup.py
- pytest --cov=./
after_success:
- codecov
notifications:
  slack:
    secure: I7Dovcg2xZjyAxQ3SPRO/ZympcjUvVvX9YBTk/B3v6XuR2nAXaccYGqoxQ0pvmXciA6Wj5TTNqaJm1XTsG6UqGts8MRRApTr+3jJAnxzCsra1c9DDEX7bmTwGl1JD4Lo02udlMTSGHfoO7l7FfLdAZEJ4Hic3h8urJF70zRmW6ohrCteBG4xYUZvuZO/DTGTGbaTD894+Rn1FTXzRKHLbWw+kU0HuHLY++MJLVYH29DUgWiJ55OBkEb9U2xwxNw6lSveyyIrMEE9KQtuTo3MvyUDOktg8PYUBkrwvyb+UsgIpHm8lqTrduv9EUvF9/TYTMrHuz5bdjjdnUFhgEVSMLeTIjedEgRDaoKcAFi2yeSPjWxBIm+Xth1ndjMvrvrhC3c6LcbIjEhz3fkw9gppDIX5qf/ZF3I8avrBTpq1TuZ66W3VLlmlARuUTWHFBCln3XlcyfsrbFqO6Wwc5Ej3sMgTws43H0CWSP+O/yO4ckBz5iMKuQw54Xx43BtDHS3+gAjgERirOW7SSK5Az3CaI2GL4/tkKdnFD65P4eGiOrVSg28RZxssjkTHtObZJ2mHwKIAI7KyBgSmJ1Md7VMOf+ah/hLDAOl1B2Wz9aH0NH1Hs84cD0EIL7wmpHV2/jI/gBDvQ9dRlXS1sua4nV4DN761fAecVaiBrcjd/9m5hyY=
