dist: xenial
language: python
python: 3.7
install:
- pip install -r requirements.txt
script:
- flake8 kdlc/ tests/ setup.py
- black --check kdlc tests setup.py
- pytest --cov=./
after_success:
- codecov
notifications:
  slack:
    secure: kVxgJ/SHo5RFzH272TEEtV1gLLtvbov3ts8iq5stY8NsFGWjuUthRvj1/CCBzJ5AQeRQ65N1DDG21hg/MFpoisxyGl3QHLqrk1+gF70CzMG9/CCn0DzuQSus8RWmpXpPUPTwU14rWChuqEwW46rwBCXJUciMFquRcNyi03X2vx1Z36jsplpMCsMGRzrqoNaEIIbd/ZGmKcceQegLeHnt1H82KmD6F0Guw1mHrbTGj/vXWDRg6p8wRdl84sYmWHqkjWlB8XYHt+Go9i52QVQhYFXgzFXcsKp11n/yPVUojLrptyku1j0vGKq33Oq1irEJt7mxBFoF9ZXMVW+Eu6EUTZMFc+pLDflxIhm+4jZvWnhzVuwJteB8UqLranRqNnQBbNUtVEwJGnlgqgUILhuwnEpMKzAz2NCuNCO/iUI5at0TW/HK3MIRYjFazfKzkVV6ngsYBaHqGSkYnJGoSvLthtv4hi2xpr69+AR07QRk65PjwF/i/69Jahm+YuOvfH/9PGa+gBuAN1jx+dQBFRN2LgENioEPyWcKTK9zOyWRBAXE50kGcG+avFXdLCDIjVEIlCYSWYjADKh8aY4tU3grcCGaB50QGaUcNnzNBocKbRHPr2PUvPkSxl23SsovzzkVCwhi0wvPaGUhw0Bzj+8xBxUu6GPVES3k25eRmdZtpl4=
    rooms:
      secure: K7Tg+1sqo9vwgXKjdCeJERMxlyRalxBiYTNKMU8r3kI+WAfzCULT5jyf1ESLBZI2sLY2H5Ozrrlkib2+5R1lbtxh9zoZ9GetHLS1GQSO+UBvPVPnkY9MOVM05gjtyurU3CPksJhg3c4aGHxX6vljqM6E7ykAKSnPwvTMn2L8YJzeFpeX6419iCy/xzrq+e3aXhCIvbYS+qXqFbjvS4vnk2FIURosc4NGeyzdLk5B9fwVqVSNwAF8XBEjMWRvOcpLOjTGpWjY7VqiL637tIiogFqMVDDuJin2DLnyF4f0lg+tevJHU3Vz+V46QxsXJBwtWDdwbp1V2Wd5fnSaQSdV6bgpfW9FFsroAvfJKMwwlxzCq30d3D1iqGGtCgSCtj1ewj0J4GEtSdALxiod+8KJ3TWR+/Ui8c3dfxcP3SlmSwqC6qTZWct/p4rlbZ6TDfSs1axXtXU7Cka8JCAjA5kgBAFCv4j7Nv7sKlkxkyKgjyo6iJzLghpkHRW7NlfLI+AYXExXu2a66RzDQ6gggkvWeS2cCQ3r53paSrpo5OatpDVJteg3wPGV6alrUqM4+lw+DFrEsYmo3XJFq5jT7TH+pQGEqVAsdE1iFF8tVuwsxmf7vgTb+etRWHJA3g4Hqog2etJND+H6EYe1YYS+inrBDYEjDecPX3xDFNZ4K9wBdpk=
